# Generated by Django 4.0.3 on 2022-03-05 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0002_alter_members_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='members',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoApi.missiongroups'),
        ),
    ]
