# Generated by Django 4.0.3 on 2022-03-06 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0005_alter_members_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='member',
            new_name='associate',
        ),
    ]
